Adding setinels again

diff --git a/core/gamescope-script b/core/gamescope-script
--- a/core/gamescope-script
+++ b/core/gamescope-script
@@ -24,6 +24,7 @@ export HOMETEST_DESKTOP_USER=gamer
 export HOMETEST_DESKTOP_SESSION=gnome
 
 # Gamescope specific configuration
+export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
 export GAMESCOPE_DISABLE_ASYNC_FLIPS=1
 export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)
 export STEAM_GAMESCOPE_VRR_SUPPORTED=1
@@ -65,6 +66,14 @@ export vk_xwayland_wait_ready=false
 export DXVK_HDR=1
 export STEAM_GAMESCOPE_HDR_SUPPORTED=1
 export ENABLE_GAMESCOPE_WSI=1
+
+# Steam OS Sentinels ----------------------------------------------------
+# Workaround for steam getting killed immediatly during reboot
+export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
+
+# Workaround for steam getting killed immediatly during shutdown
+# Same idea as reboot sentinel above
+export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
 
 # Cursor configuration
 CURSOR_FILE="${HOME}/.local/share/Steam/tenfoot/resource/images/cursors/arrow_right.png"
@@ -161,3 +170,40 @@ $STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1
 
 # When the client exits, kill gamescope nicely
 kill $gamescope_pid
+
+# Start a background sleep for five seconds because we don't trust it
+sleep 5 &
+sleep_pid="$!"
+
+# Catch reboot and poweroof sentinels here
+if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
+	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
+	reboot
+fi
+if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
+	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
+	poweroff
+fi
+
+# Wait for gamescope or the sleep to finish for timeout purposes
+ret=0
+wait -n $gamescope_pid $sleep_pid || ret=$?
+
+# If we get a SIGTERM/etc while waiting this happens.  Proceed to kill -9 everything but complain
+if [[ $ret = 127 ]]; then
+	echo >&2 "gamescope-session: Interrupted while waiting on teardown, force-killing remaining tasks"
+fi
+
+# Kill all remaining jobs and warn if unexpected things are in there (should be just sleep_pid, unless gamescope failed
+# to exit in time or we hit the interrupt case above)
+for job in $(jobs -p); do
+	# Warn about unexpected things
+	if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
+		echo >&2 "gamescope-session: gamescope timed out while exiting, killing"
+	elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
+		echo >&2 "gamescope-session: unexpected background pid $job at teardown: "
+		# spew some debug about it
+		ps -p "$job" >&2
+	fi
+	kill -9 "$job"
+done
